added new DaoJdbcImpls
6ALLIKA/jv-internetshop pull request #12
Opened 2020-05-13 19:20 UTC by 6ALLIKA

all functional still works on site, all was tested, for deleting product made method that give me that opportunity in orders level

2020-05-13 20:10 UTC, boroda4436 requested changes

2020-05-13 20:10 UTC, boroda4436 commented on src/main/java/ma/internetshop/dao/jdbc/OrderDaoJdbcImpl.java
> +            LOGGER.error("Can't INSERT order in mySQL internet_shop", ex);
Дублювання інформації

2020-05-13 20:10 UTC, boroda4436 commented on src/main/java/ma/internetshop/dao/jdbc/OrderDaoJdbcImpl.java
> +            LOGGER.error("Can't FIND product by ID "
.

2020-05-13 20:10 UTC, boroda4436 commented on src/main/java/ma/internetshop/dao/jdbc/OrderDaoJdbcImpl.java
> +            LOGGER.error("Can't SELECT orders in mySQL internet_shop", ex);
.

2020-05-13 20:10 UTC, boroda4436 commented on src/main/java/ma/internetshop/dao/jdbc/OrderDaoJdbcImpl.java
> +            LOGGER.error("Can't UPDATE order by ID "
.

2020-05-13 20:10 UTC, boroda4436 commented on src/main/java/ma/internetshop/dao/jdbc/OrderDaoJdbcImpl.java
> +            LOGGER.error("Can't FIND user from order by ID "
.

2020-05-13 20:10 UTC, boroda4436 commented on src/main/java/ma/internetshop/dao/jdbc/OrderDaoJdbcImpl.java
> +        return new Order(orderId, getProductsOfOrder(orderId), getUserOfOrder(userId));
```suggestion
        return new Order(orderId, getProductsOfOrder(orderId), userId);
```
Можна було зробити так

2020-05-13 20:10 UTC, boroda4436 commented on src/main/java/ma/internetshop/dao/jdbc/OrderDaoJdbcImpl.java
> +            int resultSet = statement.executeUpdate();
```suggestion
            int ???? = statement.executeUpdate();
```
Точно ім'я змінної resultSet тут підходить?

2020-05-13 20:10 UTC, boroda4436 commented on src/main/java/ma/internetshop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +    private User getUserOfShoppingCart(Long userId) {
Так само як і в Order - можна замінити User на userId і тоді цей метод не потрібно

2020-05-13 20:10 UTC, boroda4436 commented on src/main/java/ma/internetshop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +            String userLogin = resultSet.getString("user_login");
Дивні назви колонок) і так ясно що це логін для юзера

2020-05-13 20:10 UTC, boroda4436 commented on src/main/java/ma/internetshop/dao/jdbc/UserDaoJdbcImpl.java
> +        String query = "INSERT INTO users (user_name, user_login, user_pass) VALUES (?, ?, ?);";
```suggestion
        String query = "INSERT INTO users (user_name, login, pass) VALUES (?, ?, ?);";
```

2020-05-13 20:50 UTC, 6ALLIKA commented on src/main/java/ma/internetshop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +            String userLogin = resultSet.getString("user_login");
Я отталкиваюсь от логики айдишника) показалось разумный и понятным)

2020-05-13 20:50 UTC, 6ALLIKA commented on src/main/java/ma/internetshop/dao/jdbc/UserDaoJdbcImpl.java
> +        String query = "INSERT INTO users (user_name, user_login, user_pass) VALUES (?, ?, ?);";
Я по другому юзера не сделаю, или сделать конструктор для него без пароля?

2020-05-13 20:51 UTC, 6ALLIKA commented on src/main/java/ma/internetshop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +    private User getUserOfShoppingCart(Long userId) {
Если мы пошли без каскада, то и решил и юзера на айди не менять)

2020-05-13 20:52 UTC, 6ALLIKA commented on src/main/java/ma/internetshop/dao/jdbc/OrderDaoJdbcImpl.java
> +        return new Order(orderId, getProductsOfOrder(orderId), getUserOfOrder(userId));
Ответил ниже

2020-05-13 20:52 UTC, 6ALLIKA commented on src/main/java/ma/internetshop/dao/jdbc/OrderDaoJdbcImpl.java
> +            int resultSet = statement.executeUpdate();
Да, не корректно пожалуй)

2020-05-14 06:47 UTC, 6ALLIKA commented on src/main/java/ma/internetshop/dao/jdbc/UserDaoJdbcImpl.java
> +        String query = "INSERT INTO users (user_name, user_login, user_pass) VALUES (?, ?, ?);";
по неймингу ответил выше, как по мне легче таким образом ориентироваться, но если это принципиально важная информация я ее поменяю, если не очень, то учту в будущем)

2020-05-14 13:11 UTC, boroda4436 commented on src/main/java/ma/internetshop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +    private User getUserOfShoppingCart(Long userId) {
а як це пов'язано?

2020-05-14 13:11 UTC, boroda4436 commented on src/main/java/ma/internetshop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +            String userLogin = resultSet.getString("user_login");
обсудили це питання на лекції

2020-05-14 13:13 UTC, boroda4436 commented on src/main/java/ma/internetshop/dao/jdbc/OrderDaoJdbcImpl.java
> +            int resultSet = statement.executeUpdate();
то перейменуємо?

2020-05-14 13:14 UTC, 6ALLIKA commented on src/main/java/ma/internetshop/dao/jdbc/OrderDaoJdbcImpl.java
> +            int resultSet = statement.executeUpdate();
ай блин

2020-05-14 13:14 UTC, 6ALLIKA commented on src/main/java/ma/internetshop/dao/jdbc/OrderDaoJdbcImpl.java
> +            int resultSet = statement.executeUpdate();
провтыкал, извиняюсь)

2020-05-14 13:14 UTC, 6ALLIKA commented on src/main/java/ma/internetshop/dao/jdbc/ShoppingCartDaoJdbcImpl.java
> +    private User getUserOfShoppingCart(Long userId) {
ну, по сложному пути, имелось ввиду)

2020-05-14 14:51 UTC, boroda4436 commented on src/main/java/ma/internetshop/dao/jdbc/OrderDaoJdbcImpl.java
> +                + "FROM orders_products INNER JOIN products "
можна заюзати aliases
```suggestion
                + "FROM orders_products op INNER JOIN products p "
```

2020-05-14 14:52 UTC, boroda4436 approved these changes

2020-05-14 20:23 UTC, lord-dwarf approved these changes

2020-05-14 20:23 UTC, polinakulyk commented
ntfctn tst

2020-05-19 13:28 UTC, merged