Version2.0
6ALLIKA/jv-internetshop pull request #2
Opened 2020-04-23 16:13 UTC by 6ALLIKA

2020-04-23 16:15 UTC, 6ALLIKA commented
вроде трэвис заработал)

2020-04-23 18:16 UTC, vztot approved these changes
Good job!

2020-04-24 08:05 UTC, Sofasmile commented on src/main/java/ma/internetshop/dao/OrderDao.java
> +    Order create(List<Product> products, User user);
```suggestion
    Order create(Order order);
```

2020-04-24 08:05 UTC, Sofasmile commented on src/main/java/ma/internetshop/dao/ShoppingCartDao.java
> +    List<Product> getAllProducts(ShoppingCart shoppingCart);
цей метод на рівні дао не потрібен, замість нього можна створити get(Long id)

2020-04-24 08:05 UTC, Sofasmile commented on src/main/java/ma/internetshop/dao/impl/OrderDaoImpl.java
> +        Order order = new Order(products, user);
потрібно змінити відповідно до сигнатури інтерфейсу

2020-04-24 08:05 UTC, Sofasmile commented on src/main/java/ma/internetshop/dao/impl/ShoppingCartDaoImpl.java
> +        if (!isExist) {
цю логіку можна винести в рівень сервісу

2020-04-24 08:05 UTC, Sofasmile commented on src/main/java/ma/internetshop/service/impl/OrderServiceImpl.java
> +        return orderDao.create(products, user);
тут також потрібно чистити корзину

2020-04-24 08:05 UTC, Sofasmile commented on src/main/java/ma/internetshop/service/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart createdCart = shoppingCartDao.create(shoppingCart);
а що якщо вона уже створена?

2020-04-24 08:05 UTC, Sofasmile commented on src/main/java/ma/internetshop/service/impl/ShoppingCartServiceImpl.java
> +        return shoppingCart.getProducts().removeIf(prod -> prod.getId().equals(product.getId()));
тут круто було б викликати метод update після видалення товару

2020-04-24 09:37 UTC, 6ALLIKA commented on src/main/java/ma/internetshop/service/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart createdCart = shoppingCartDao.create(shoppingCart);
она внутри проходила проверку)

2020-04-24 09:39 UTC, 6ALLIKA commented on src/main/java/ma/internetshop/service/impl/OrderServiceImpl.java
> +        return orderDao.create(products, user);
тогда в таком случае должна быть другая сигнатура, что бы это имело логичный вид

2020-04-24 11:57 UTC, boroda4436 requested changes

2020-04-24 11:57 UTC, boroda4436 commented on src/main/java/ma/internetshop/dao/ShoppingCartDao.java
> +    List<Product> getAllProducts(ShoppingCart shoppingCart);
@6ALLIKA ?

2020-04-24 13:05 UTC, merged